apiVersion: apps/v1
kind: Deployment
metadata:
  name: serhat-frontend
  labels:
    app: serhat-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serhat-frontend
  template:
    metadata:
      labels:
        app: serhat-frontend
    spec:
      containers:
        - name: frontend
          image: serhatbilge/guestbook-frontend:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
