apiVersion: apps/v1
kind: Deployment
metadata:
  name: serhat-frontend
  labels:
    app: serhat-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serhat-frontend
  template:
    metadata:
      labels:
        app: serhat-frontend
    spec:
      containers:
        - name: frontend
          image: serhatbilge/guestbook-frontend:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: nginx-api-conf
              mountPath: /opt/app-root/etc/nginx.default.d/serhat-api.conf
              subPath: serhat-api.conf
              readOnly: true
      volumes:
        - name: nginx-api-conf
          configMap:
            name: serhat-frontend-nginx-api
