apiVersion: apps/v1
kind: Deployment
metadata:
  name: serhat-postgres
  labels:
    app: serhat-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serhat-postgres
  template:
    metadata:
      labels:
        app: serhat-postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/fedora/postgresql-16:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: serhat-postgres-secret
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: serhat-postgres-secret
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: serhat-postgres-secret
                  key: POSTGRESQL_DATABASE
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: serhat-postgres-pvc
