apiVersion: apps/v1
kind: Deployment
metadata:
  name: serhat-redis
  labels:
    app: serhat-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serhat-redis
  template:
    metadata:
      labels:
        app: serhat-redis
    spec:
      containers:
        - name: redis
          image: quay.io/kurs/redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: serhat-redis-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis/data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: serhat-redis-pvc
